---
  title: "diversity_global_aquatic_insect"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Description of figures
```{r}
# Note that I used ArcMap to make Fig2 a,b,c,d ,Fig3, Extended Fig2, Extended Fig3

# And I used Adobe Photoshop 2020 to generate Fig.1,  Fig.5. and enhanced Fig.4, Fig.6.

```

# Fig.2 e,f,g,h
```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(corrr)
library(tmap)
library(spdep)
library(tigris)
library(rmapshaper)
library(flextable)
library(car)
library(spatialreg)
library(stargazer)
library(spatialreg)
library(spdep)
library(gcookbook)
library(ggplot2)
library(ggthemes)

shp=st_read("Global basin.shp")
valid_shapefile <- st_make_valid(shp)
basins_boundaries <- st_geometry(valid_shapefile)
basins_centroids <- st_centroid(basins_boundaries)
valid_shapefile$average_latitude <- st_coordinates(basins_centroids)[, 2]
latitude=valid_shapefile[which(valid_shapefile$HYBAS_ID %in% data$HYBAS_ID), c(1,17)]
latitude=as.data.frame(latitude[,c(1:2)])
colnames(data)[1] <- "HYBAS_ID"
latitude_data=merge(data, latitude,  by = "HYBAS_ID")
L_data=latitude_data[,c(1:3,6,7,56)]


#TDq0

ggplot(L_data, aes(x = average_latitude, y = TDq0)) +
  geom_point(color = "#7acfff", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "steelblue3", fill = "skyblue") +
  labs(x = "average_latitude", y = "TDq0", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_TDq0new.pdf", height = 4, width = 7)

#TDq1

ggplot(L_data, aes(x = average_latitude, y = TDq1)) +
  geom_point(color = "#7acfff", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "steelblue3", fill = "skyblue") +
  labs(x = "average_latitude", y = "TDq1", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_TDq1new.pdf", height = 4, width = 7)

#FDq0

ggplot(L_data, aes(x = average_latitude, y = FDq0)) +
  geom_point( color = "orange", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "tomato1",fill="#ffbd88")+
  labs(x = "average_latitude", y = "FDq0", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_FDq0new.pdf", height = 4, width = 7)

#FDq1

ggplot(L_data, aes(x = average_latitude, y = FDq1)) +
  geom_point( color = "orange", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "tomato1",fill="#ffbd88")+
  labs(x = "average_latitude", y = "FDq1", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_FDq1new.pdf", height = 4, width = 7)
```

# Before Fig.4 a,b,c,d
```{r}
feow=read.csv("feow_data.csv",header = T)

unique=unique(feow$MHT_TXT)
value_counts <- table(feow$MHT_TXT)
unique_num=data.frame(unique,value_counts)

Box_data=merge(feow,data[,c(1:3,6,7)],by = "HYBAS_ID")
Box_data <- subset(Box_data, !(MHT_TXT %in% c("Large River Deltas", "Oceanic Island")))

library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggsignif)
library(rstatix)

TSCR=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Coastal Rivers"),]
TSF=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Floodplain Rivers and Wetland Complexes"),]
TUR=Box_data[which(Box_data$MHT_TXT=="Temperate Upland Rivers"),]
MF=Box_data[which(Box_data$MHT_TXT=="Montane Freshwaters"),]
TCR=Box_data[which(Box_data$MHT_TXT=="Temperate Coastal Rivers"),]
XF=Box_data[which(Box_data$MHT_TXT=="Xeric Freshwaters and Endorheic Basins"),]
TSUR=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Upland Rivers"),]
LL=Box_data[which(Box_data$MHT_TXT=="Large Lakes"),]
TFR=Box_data[which(Box_data$MHT_TXT=="Temperate Floodplain Rivers and Wetlands"),]
PF=Box_data[which(Box_data$MHT_TXT=="Polar Freshwaters"),]
```

# Fig. 4a
```{r}
data_TSCR_TDq0=TSCR$TDq0
data_TSF_TDq0=TSF$TDq0
data_TUR_TDq0=TUR$TDq0
data_MF_TDq0=MF$TDq0
data_TCR_TDq0=TCR$TDq0
data_XF_TDq0=XF$TDq0
data_TSUR_TDq0=TSUR$TDq0
data_LL_TDq0=LL$TDq0
data_TFR_TDq0=TFR$TDq0
data_PF_TDq0=PF$TDq0


max_length_TDq0=max(length(data_TSCR_TDq0),length(data_TSF_TDq0),length(data_TUR_TDq0),
                    length(data_MF_TDq0),length(data_TCR_TDq0),length(data_XF_TDq0),
                    length(data_TSUR_TDq0),length(data_LL_TDq0),length(data_TFR_TDq0),
                    length(data_PF_TDq0))

data_TSCR_TDq0_padded <- c(data_TSCR_TDq0, rep(NA, max_length_TDq0 - length(data_TSCR_TDq0)))
data_TSF_TDq0_padded <- c(data_TSF_TDq0, rep(NA, max_length_TDq0 - length(data_TSF_TDq0)))
data_TUR_TDq0_padded <- c(data_TUR_TDq0, rep(NA, max_length_TDq0 - length(data_TUR_TDq0)))
data_MF_TDq0_padded <- c(data_MF_TDq0, rep(NA, max_length_TDq0 - length(data_MF_TDq0)))
data_TCR_TDq0_padded <- c(data_TCR_TDq0, rep(NA, max_length_TDq0 - length(data_TCR_TDq0)))
data_XF_TDq0_padded <- c(data_XF_TDq0, rep(NA, max_length_TDq0 - length(data_XF_TDq0)))
data_TSUR_TDq0_padded <- c(data_TSUR_TDq0, rep(NA, max_length_TDq0 - length(data_TSUR_TDq0)))
data_LL_TDq0_padded <- c(data_LL_TDq0, rep(NA, max_length_TDq0 - length(data_LL_TDq0)))
data_TFR_TDq0_padded <- c(data_TFR_TDq0, rep(NA, max_length_TDq0 - length(data_TFR_TDq0)))
data_PF_TDq0_padded <- c(data_PF_TDq0, rep(NA, max_length_TDq0 - length(data_PF_TDq0)))


TDq0_DATA <- data.frame(TSCR=data_TSCR_TDq0_padded,
                        TSF=data_TSF_TDq0_padded,
                        TUR=data_TUR_TDq0_padded,
                        MF=data_MF_TDq0_padded,
                        TCR=data_TCR_TDq0_padded,
                        XF=data_XF_TDq0_padded,
                        TSUR=data_TSUR_TDq0_padded,
                        LL=data_LL_TDq0_padded,
                        TFR=data_TFR_TDq0_padded,
                        PF=data_PF_TDq0_padded)

Box_TDq0 <-Box_data[,c(2,3)] 
Box_TDq0$MHT_TXT <- factor(Box_TDq0$MHT_TXT )

stat.test <- Box_TDq0 %>%
  mutate(TDq0 = as.numeric(as.character(TDq0))) %>%
  wilcox_test(
    TDq0 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_TDq0)+
  geom_boxplot(aes(MHT_TXT, TDq0, color= MHT_TXT))+
  scale_color_manual(values = colors)+
  xlab("")+
  theme_classic()+
  labs(title = "TDq0")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

TDq0_DATA_no_na <- replace(TDq0_DATA, is.na(TDq0_DATA), -Inf)

y_value <- rep(apply(TDq0_DATA_no_na, 2, max)[1:9], 9:1) + 0

y_value <- y_value + c(3*1:9, 3*1:8, 3*1:7, 3*1:6,3*1:5, 3*1:4, 3*1:3, 3*1:2, 3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("TDq0.pdf", height = 6, width = 7)
```

# Fig. 4b
```{r}
data_TSCR_TDq1=TSCR$TDq1
data_TSF_TDq1=TSF$TDq1
data_TUR_TDq1=TUR$TDq1
data_MF_TDq1=MF$TDq1
data_TCR_TDq1=TCR$TDq1
data_XF_TDq1=XF$TDq1
data_TSUR_TDq1=TSUR$TDq1
data_LL_TDq1=LL$TDq1
data_TFR_TDq1=TFR$TDq1
data_PF_TDq1=PF$TDq1


max_length_TDq1=max(length(data_TSCR_TDq1),length(data_TSF_TDq1),length(data_TUR_TDq1),
                    length(data_MF_TDq1),length(data_TCR_TDq1),length(data_XF_TDq1),
                    length(data_TSUR_TDq1),length(data_LL_TDq1),length(data_TFR_TDq1),
                    length(data_PF_TDq1))

data_TSCR_TDq1_padded <- c(data_TSCR_TDq1, rep(NA, max_length_TDq1 - length(data_TSCR_TDq1)))
data_TSF_TDq1_padded <- c(data_TSF_TDq1, rep(NA, max_length_TDq1 - length(data_TSF_TDq1)))
data_TUR_TDq1_padded <- c(data_TUR_TDq1, rep(NA, max_length_TDq1 - length(data_TUR_TDq1)))
data_MF_TDq1_padded <- c(data_MF_TDq1, rep(NA, max_length_TDq1 - length(data_MF_TDq1)))
data_TCR_TDq1_padded <- c(data_TCR_TDq1, rep(NA, max_length_TDq1 - length(data_TCR_TDq1)))
data_XF_TDq1_padded <- c(data_XF_TDq1, rep(NA, max_length_TDq1 - length(data_XF_TDq1)))
data_TSUR_TDq1_padded <- c(data_TSUR_TDq1, rep(NA, max_length_TDq1 - length(data_TSUR_TDq1)))
data_LL_TDq1_padded <- c(data_LL_TDq1, rep(NA, max_length_TDq1 - length(data_LL_TDq1)))
data_TFR_TDq1_padded <- c(data_TFR_TDq1, rep(NA, max_length_TDq1 - length(data_TFR_TDq1)))
data_PF_TDq1_padded <- c(data_PF_TDq1, rep(NA, max_length_TDq1 - length(data_PF_TDq1)))


TDq1_DATA <- data.frame(TSCR=data_TSCR_TDq1_padded,
                        TSF=data_TSF_TDq1_padded,
                        TUR=data_TUR_TDq1_padded,
                        MF=data_MF_TDq1_padded,
                        TCR=data_TCR_TDq1_padded,
                        XF=data_XF_TDq1_padded,
                        TSUR=data_TSUR_TDq1_padded,
                        LL=data_LL_TDq1_padded,
                        TFR=data_TFR_TDq1_padded,
                        PF=data_PF_TDq1_padded)

Box_TDq1 <-Box_data[,c(2,4)] 
Box_TDq1$MHT_TXT <- factor(Box_TDq1$MHT_TXT )

stat.test <- Box_TDq1 %>%
  mutate(TDq1 = as.numeric(as.character(TDq1))) %>%
  wilcox_test(
    TDq1 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_TDq1)+
  geom_boxplot(aes(MHT_TXT, TDq1, color= MHT_TXT))+
  scale_color_manual(values = colors)+
  xlab("")+
  theme_classic()+
  labs(title = "TDq1")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

TDq1_DATA_no_na <- replace(TDq1_DATA, is.na(TDq1_DATA), -Inf)

y_value <- rep(apply(TDq1_DATA_no_na, 2, max)[1:9], 9:1) + 0

y_value <- y_value + c(3*1:9, 3*1:8, 3*1:7, 3*1:6,3*1:5, 3*1:4, 3*1:3, 3*1:2, 3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("TDq1.pdf", height = 6, width = 7)
```

# Fig. 4c
```{r}
data_TSCR_FDq0=TSCR$FDq0
data_TSF_FDq0=TSF$FDq0
data_TUR_FDq0=TUR$FDq0
data_MF_FDq0=MF$FDq0
data_TCR_FDq0=TCR$FDq0
data_XF_FDq0=XF$FDq0
data_TSUR_FDq0=TSUR$FDq0
data_LL_FDq0=LL$FDq0
data_TFR_FDq0=TFR$FDq0
data_PF_FDq0=PF$FDq0


max_length_FDq0=max(length(data_TSCR_FDq0),length(data_TSF_FDq0),length(data_TUR_FDq0),
                    length(data_MF_FDq0),length(data_TCR_FDq0),length(data_XF_FDq0),
                    length(data_TSUR_FDq0),length(data_LL_FDq0),length(data_TFR_FDq0),
                    length(data_PF_FDq0))

data_TSCR_FDq0_padded <- c(data_TSCR_FDq0, rep(NA, max_length_FDq0 - length(data_TSCR_FDq0)))
data_TSF_FDq0_padded <- c(data_TSF_FDq0, rep(NA, max_length_FDq0 - length(data_TSF_FDq0)))
data_TUR_FDq0_padded <- c(data_TUR_FDq0, rep(NA, max_length_FDq0 - length(data_TUR_FDq0)))
data_MF_FDq0_padded <- c(data_MF_FDq0, rep(NA, max_length_FDq0 - length(data_MF_FDq0)))
data_TCR_FDq0_padded <- c(data_TCR_FDq0, rep(NA, max_length_FDq0 - length(data_TCR_FDq0)))
data_XF_FDq0_padded <- c(data_XF_FDq0, rep(NA, max_length_FDq0 - length(data_XF_FDq0)))
data_TSUR_FDq0_padded <- c(data_TSUR_FDq0, rep(NA, max_length_FDq0 - length(data_TSUR_FDq0)))
data_LL_FDq0_padded <- c(data_LL_FDq0, rep(NA, max_length_FDq0 - length(data_LL_FDq0)))
data_TFR_FDq0_padded <- c(data_TFR_FDq0, rep(NA, max_length_FDq0 - length(data_TFR_FDq0)))
data_PF_FDq0_padded <- c(data_PF_FDq0, rep(NA, max_length_FDq0 - length(data_PF_FDq0)))


FDq0_DATA <- data.frame(TSCR=data_TSCR_FDq0_padded,
                        TSF=data_TSF_FDq0_padded,
                        TUR=data_TUR_FDq0_padded,
                        MF=data_MF_FDq0_padded,
                        TCR=data_TCR_FDq0_padded,
                        XF=data_XF_FDq0_padded,
                        TSUR=data_TSUR_FDq0_padded,
                        LL=data_LL_FDq0_padded,
                        TFR=data_TFR_FDq0_padded,
                        PF=data_PF_FDq0_padded)

Box_FDq0 <-Box_data[,c(2,5)] 
Box_FDq0$MHT_TXT <- factor(Box_FDq0$MHT_TXT )

stat.test <- Box_FDq0 %>%
  mutate(FDq0 = as.numeric(as.character(FDq0))) %>%
  wilcox_test(
    FDq0 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_FDq0)+
  geom_boxplot(aes(MHT_TXT, FDq0, color= MHT_TXT))+
  scale_color_manual(values = colors)+
  xlab("")+
  theme_classic()+
  labs(title = "FDq0")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

FDq0_DATA_no_na <- replace(FDq0_DATA, is.na(FDq0_DATA), -Inf)

y_value <- rep(apply(FDq0_DATA_no_na, 2, max)[1:9], 9:1) + 2

y_value <- y_value + c(0.5*1:9, 0.5*1:8, 0.5*1:7, 0.5*1:6,0.5*1:5, 0.5*1:4, 0.5*1:1, 0.5*1:2, 0.5)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("FDq0.pdf", height = 6, width = 7)
```

# Fig. 4d
```{r}
data_TSCR_FDq1=TSCR$FDq1
data_TSF_FDq1=TSF$FDq1
data_TUR_FDq1=TUR$FDq1
data_MF_FDq1=MF$FDq1
data_TCR_FDq1=TCR$FDq1
data_XF_FDq1=XF$FDq1
data_TSUR_FDq1=TSUR$FDq1
data_LL_FDq1=LL$FDq1
data_TFR_FDq1=TFR$FDq1
data_PF_FDq1=PF$FDq1


max_length_FDq1=max(length(data_TSCR_FDq1),length(data_TSF_FDq1),length(data_TUR_FDq1),
                    length(data_MF_FDq1),length(data_TCR_FDq1),length(data_XF_FDq1),
                    length(data_TSUR_FDq1),length(data_LL_FDq1),length(data_TFR_FDq1),
                    length(data_PF_FDq1))

data_TSCR_FDq1_padded <- c(data_TSCR_FDq1, rep(NA, max_length_FDq1 - length(data_TSCR_FDq1)))
data_TSF_FDq1_padded <- c(data_TSF_FDq1, rep(NA, max_length_FDq1 - length(data_TSF_FDq1)))
data_TUR_FDq1_padded <- c(data_TUR_FDq1, rep(NA, max_length_FDq1 - length(data_TUR_FDq1)))
data_MF_FDq1_padded <- c(data_MF_FDq1, rep(NA, max_length_FDq1 - length(data_MF_FDq1)))
data_TCR_FDq1_padded <- c(data_TCR_FDq1, rep(NA, max_length_FDq1 - length(data_TCR_FDq1)))
data_XF_FDq1_padded <- c(data_XF_FDq1, rep(NA, max_length_FDq1 - length(data_XF_FDq1)))
data_TSUR_FDq1_padded <- c(data_TSUR_FDq1, rep(NA, max_length_FDq1 - length(data_TSUR_FDq1)))
data_LL_FDq1_padded <- c(data_LL_FDq1, rep(NA, max_length_FDq1 - length(data_LL_FDq1)))
data_TFR_FDq1_padded <- c(data_TFR_FDq1, rep(NA, max_length_FDq1 - length(data_TFR_FDq1)))
data_PF_FDq1_padded <- c(data_PF_FDq1, rep(NA, max_length_FDq1 - length(data_PF_FDq1)))


FDq1_DATA <- data.frame(TSCR=data_TSCR_FDq1_padded,
                        TSF=data_TSF_FDq1_padded,
                        TUR=data_TUR_FDq1_padded,
                        MF=data_MF_FDq1_padded,
                        TCR=data_TCR_FDq1_padded,
                        XF=data_XF_FDq1_padded,
                        TSUR=data_TSUR_FDq1_padded,
                        LL=data_LL_FDq1_padded,
                        TFR=data_TFR_FDq1_padded,
                        PF=data_PF_FDq1_padded)

Box_FDq1 <-Box_data[,c(2,6)] 
Box_FDq1$MHT_TXT <- factor(Box_FDq1$MHT_TXT )

stat.test <- Box_FDq1 %>%
  mutate(FDq1 = as.numeric(as.character(FDq1))) %>%
  wilcox_test(
    FDq1 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_FDq1)+
  geom_boxplot(aes(MHT_TXT, FDq1, color= MHT_TXT))+
  scale_color_manual(values = colors)+
  xlab("")+
  theme_classic()+
  labs(title = "FDq1")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

FDq1_DATA_no_na <- replace(FDq1_DATA, is.na(FDq1_DATA), -Inf)

y_value <- rep(apply(FDq1_DATA_no_na, 2, max)[1:9], 9:1) + 1

y_value <- y_value + c(0.3*1:9, 0.3*1:8, 0.3*1:7, 0.3*1:6,0.3*1:5, 0.3*1:4, 0.3*1:1, 0.3*1:2, 0.3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("FDq1.pdf", height = 6, width = 7)
```

# Fig. 5
```{r}
library(vegan)
library(ggvenn)
enm=read.csv("env.csv",head=T)
merged_diversity=read.csv("Bio_all.csv",header = T)

colnames(merged_diversity)[1] <- "HYBAS_ID"
data <- merge(merged_diversity, enm, by= "HYBAS_ID")
enm.hy=data[,c(12:14,17,19)]
enm.cl=data[,c(21,22,28,32,35)]
enm.ge=data[,c(40,42,44:46)]
enm.an=data[,c(49:53)]


par(mfrow=c(2,2))

# Taxonomic diversity (q=0) 
vpa.TDq0_mid=varpart(data[,2],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.TDq0_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

# Taxonomic diversity (q=1)
vpa.TDq1_mid=varpart(data[,3],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.TDq1_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

# Functional diversity (q=0) 
vpa.FDq0_mid=varpart(data[,6],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.FDq0_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

# Functional diversity (q=0) 
vpa.FDq1_mid=varpart(data[,7],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.FDq1_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

colnames(enm.hy)
colnames(enm.cl)
colnames(enm.ge)
colnames(enm.an)

```

# Fig.6a
```{r}
library(ggplot2)
library(ggthemes)
library(ggtext)

# SAR.csv is a merger of SAR_TDq0,SAR_TDq1,SAR_FDq0,SAR_TDq0
SAR_data=read.csv("SAR.csv",header = T)

data.o=SAR_data[,c(1,2,6,7,9)]
data.o$sig <- ""
data.o$sig[data.o$Pr...z.. < 0.001] <- "***"
data.o$sig[data.o$Pr...z.. >= 0.001 & data.o$Pr...z.. < 0.01] <- "**"
data.o$sig[data.o$Pr...z.. >= 0.01 & data.o$Pr...z.. < 0.05] <- "*"


# plot
data_TDq0=data.o[which(data.o$bioindex=="TDq0"),]
min=data_TDq0$Estimate-data_TDq0$Std..Error
med=data_TDq0$Estimate
max=data_TDq0$Estimate+data_TDq0$Std..Error

data.p_TDq0=as.data.frame(cbind(min, med, max))
data.p_TDq0$x=data_TDq0$var
data.p_TDq0$x <- factor(data.p_TDq0$x, levels  = rev(unique(data.p_TDq0$x)))

#### stop and check manually

data.p_TDq0$group <- paste0("group", c(rep(1, 2), rep(2, 5),
                                rep(3, 2), rep(4, 4)
                                ))
data.p_TDq0$group_col <- c(rep("darkseagreen", 2), rep("#78bee5", 5),
                    rep("#e7a40e", 2), rep("lightpink", 4))

data.p_TDq0$p<- ifelse(data_TDq0$Pr...z.. < 0.001, "***",
                ifelse(data_TDq0$Pr...z..< 0.01, "**",
                       ifelse(data_TDq0$Pr...z..< 0.05, "*", "")))

data.p_TDq0$p_col[which(data.p_TDq0$p == "*" & data.p_TDq0$med <= 0)] <- "Negtive effect(P<0.05)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "**" & data.p_TDq0$med <= 0)] <- "Negtive effect(P<0.01)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "***" & data.p_TDq0$med <= 0)] <- "Negtive effect(P<0.001)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "" & data.p_TDq0$med <= 0)] <- "Negtive effect(P>=0.05)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "*" & data.p_TDq0$med >= 0)] <- "Postive effect(P<0.05)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "**" & data.p_TDq0$med >= 0)] <- "Postive effect(P<0.01)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "***" & data.p_TDq0$med >= 0)] <- "Postive effect(P<0.001)"
data.p_TDq0$p_col[which(data.p_TDq0$p == "" & data.p_TDq0$med >= 0)] <- "Postive effect(P>=0.05)"

p_TDq0 <- ggplot(data.p_TDq0)+
  
  geom_hline(yintercept = 0, linewidth = 0.8)+
  
  geom_linerange(aes(x, ymin = min, ymax = max, color = p_col), size=1.0,show.legend = F)+
 
  geom_point(aes(x, med, color = p_col),size=3.0) +
  
  geom_text(aes(x, y = max + 1.1, label = p, color =p_col ),size=5, show.legend = F)+
  
  scale_color_manual(name = "",
                     values = c("Negtive effect(P<0.001)"="dodgerblue4",
                                "Negtive effect(P<0.01)"="steelblue3",
                                "Negtive effect(P<0.05)"= "#7acfff",
                                "Negtive effect(P>=0.05)"="lightblue2",
                                "Postive effect(P<0.001)"="tomato1",
                                "Postive effect(P<0.01)"="orange",
                                "Postive effect(P<0.05)"="#ffbd88",
                                "Postive effect(P>=0.05)"="moccasin"))+
annotate("rect",
           xmin = c(0.5,4.5,6.5,11.5),
           xmax = c(4.5,6.5,11.5,13.5),
           ymin = -13, ymax = 13, alpha = 0.3, fill = rev(unique(data.p_TDq0$group_col))) +

  scale_y_continuous(expand = c(0,0))+
  xlab("")+
  ylab("Standardized coefficient")+
  labs(title = "TDq0")+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),
        axis.ticks.x = element_line(colour = "black",size = 1),
        axis.ticks.y = element_line(colour = "black",size = 1),
        panel.border = element_rect(color = "black", size = 1.2, fill = NA),
        axis.title.x= element_text(face="bold", color="black",size=12),
        axis.text.x = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12, face = "bold",color = "black"))+
  coord_flip()

plot(p_TDq0)

ggsave("plots_TDq0.pdf", height = 5, width = 6.6)
```

# Fig.6b
```{r}
data_TDq1=data.o[which(data.o$bioindex=="TDq1"),]
min=data_TDq1$Estimate-data_TDq1$Std..Error
med=data_TDq1$Estimate
max=data_TDq1$Estimate+data_TDq1$Std..Error

data.p_TDq1=as.data.frame(cbind(min, med, max))
data.p_TDq1$x=data_TDq1$var
data.p_TDq1$x <- factor(data.p_TDq1$x, levels  = rev(unique(data.p_TDq1$x)))

#### stop and check manually

data.p_TDq1$group <- paste0("group", c(rep(1, 4), rep(2, 1),
                                rep(3, 3), rep(4, 3)
                                ))
data.p_TDq1$group_col <- c(rep("darkseagreen", 4), rep("#78bee5", 1),
                    rep("#e7a40e", 3), rep("lightpink", 3))

data.p_TDq1$p<- ifelse(data_TDq1$Pr...z.. < 0.001, "***",
                ifelse(data_TDq1$Pr...z..< 0.01, "**",
                       ifelse(data_TDq1$Pr...z..< 0.05, "*", "")))

data.p_TDq1$p_col[which(data.p_TDq1$p == "*" & data.p_TDq1$med <= 0)] <- "Negtive effect(P<0.05)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "**" & data.p_TDq1$med <= 0)] <- "Negtive effect(P<0.01)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "***" & data.p_TDq1$med <= 0)] <- "Negtive effect(P<0.001)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "" & data.p_TDq1$med <= 0)] <- "Negtive effect(P>=0.05)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "*" & data.p_TDq1$med >= 0)] <- "Postive effect(P<0.05)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "**" & data.p_TDq1$med >= 0)] <- "Postive effect(P<0.01)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "***" & data.p_TDq1$med >= 0)] <- "Postive effect(P<0.001)"
data.p_TDq1$p_col[which(data.p_TDq1$p == "" & data.p_TDq1$med >= 0)] <- "Postive effect(P>=0.05)"

p_TDq1 <- ggplot(data.p_TDq1)+
  
  geom_hline(yintercept = 0, linewidth = 0.8)+
  
  geom_linerange(aes(x, ymin = min, ymax = max, color = p_col), size=1.0,show.legend = F)+
 
  geom_point(aes(x, med, color = p_col),size=3.0) +
  
  geom_text(aes(x, y = max + 0.5, label = p, color =p_col ),size=5, show.legend = F)+
  
  scale_color_manual(name = "",
                     values = c("Negtive effect(P<0.001)"="dodgerblue4",
                                "Negtive effect(P<0.01)"="steelblue3",
                                "Negtive effect(P<0.05)"= "#7acfff",
                                "Negtive effect(P>=0.05)"="lightblue2",
                                "Postive effect(P<0.001)"="tomato1",
                                "Postive effect(P<0.01)"="orange",
                                "Postive effect(P<0.05)"="#ffbd88",
                                "Postive effect(P>=0.05)"="moccasin"))+
annotate("rect",
           xmin = c(0.5,3.5,6.5,7.5),
           xmax = c(3.5,6.5,7.5,11.5),
           ymin = -6, ymax = 6, alpha = 0.3, fill = rev(unique(data.p_TDq1$group_col))) +

  scale_y_continuous(expand = c(0,0))+
  xlab("")+
  ylab("Standardized coefficient")+
  labs(title = "TDq1")+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),
        axis.ticks.x = element_line(colour = "black",size = 1),
        axis.ticks.y = element_line(colour = "black",size = 1),
        panel.border = element_rect(color = "black", size = 1.2, fill = NA),
        axis.title.x= element_text(face="bold", color="black",size=12),
        axis.text.x = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12, face = "bold",color = "black"))+
  coord_flip()

plot(p_TDq1)

ggsave("plots_TDq1.pdf", height = 5, width = 6.6)
```

# Fig.6c
```{r}
data_FDq0=data.o[which(data.o$bioindex=="FDq0"),]
min=data_FDq0$Estimate-data_FDq0$Std..Error
med=data_FDq0$Estimate
max=data_FDq0$Estimate+data_FDq0$Std..Error

data.p_FDq0=as.data.frame(cbind(min, med, max))
data.p_FDq0$x=data_FDq0$var
data.p_FDq0$x <- factor(data.p_FDq0$x, levels  = rev(unique(data.p_FDq0$x)))

#### stop and check manually

data.p_FDq0$group <- paste0("group", c(rep(1, 3), rep(2, 4),
                                rep(3, 2), rep(4, 4)
                                ))
data.p_FDq0$group_col <- c(rep("darkseagreen", 3), rep("#78bee5", 4),
                    rep("#e7a40e", 2), rep("lightpink", 4))

data.p_FDq0$p<- ifelse(data_FDq0$Pr...z.. < 0.001, "***",
                ifelse(data_FDq0$Pr...z..< 0.01, "**",
                       ifelse(data_FDq0$Pr...z..< 0.05, "*", "")))

data.p_FDq0$p_col[which(data.p_FDq0$p == "*" & data.p_FDq0$med <= 0)] <- "Negtive effect(P<0.05)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "**" & data.p_FDq0$med <= 0)] <- "Negtive effect(P<0.01)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "***" & data.p_FDq0$med <= 0)] <- "Negtive effect(P<0.001)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "" & data.p_FDq0$med <= 0)] <- "Negtive effect(P>=0.05)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "*" & data.p_FDq0$med >= 0)] <- "Postive effect(P<0.05)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "**" & data.p_FDq0$med >= 0)] <- "Postive effect(P<0.01)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "***" & data.p_FDq0$med >= 0)] <- "Postive effect(P<0.001)"
data.p_FDq0$p_col[which(data.p_FDq0$p == "" & data.p_FDq0$med >= 0)] <- "Postive effect(P>=0.05)"

p_FDq0 <- ggplot(data.p_FDq0)+
  
  geom_hline(yintercept = 0, linewidth = 0.8)+
  
  geom_linerange(aes(x, ymin = min, ymax = max, color = p_col), size=1.0,show.legend = F)+
 
  geom_point(aes(x, med, color = p_col),size=3.0) +
  
  geom_text(aes(x, y = max + 0.14, label = p, color =p_col ),size=5, show.legend = F)+
  
  scale_color_manual(name = "",
                     values = c("Negtive effect(P<0.001)"="dodgerblue4",
                                "Negtive effect(P<0.01)"="steelblue3",
                                "Negtive effect(P<0.05)"= "#7acfff",
                                "Negtive effect(P>=0.05)"="lightblue2",
                                "Postive effect(P<0.001)"="tomato1",
                                "Postive effect(P<0.01)"="orange",
                                "Postive effect(P<0.05)"="#ffbd88",
                                "Postive effect(P>=0.05)"="moccasin"))+
annotate("rect",
           xmin = c(0.5,4.5,6.5,10.5),
           xmax = c(4.5,6.5,10.5,13.5),
           ymin = -1.5, ymax = 1.5, alpha = 0.3, fill = rev(unique(data.p_FDq0$group_col))) +

  scale_y_continuous(expand = c(0,0))+
  xlab("")+
  ylab("Standardized coefficient")+
  labs(title = "FDq0")+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),
        axis.ticks.x = element_line(colour = "black",size = 1),
        axis.ticks.y = element_line(colour = "black",size = 1),
        panel.border = element_rect(color = "black", size = 1.2, fill = NA),
        axis.title.x= element_text(face="bold", color="black",size=12),
        axis.text.x = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12, face = "bold",color = "black"))+
  coord_flip()

plot(p_FDq0)

ggsave("plots_FDq0.pdf", height = 5, width = 6.6)
```

# Fig.6d
```{r}
data_FDq1=data.o[which(data.o$bioindex=="FDq1"),]
min=data_FDq1$Estimate-data_FDq1$Std..Error
med=data_FDq1$Estimate
max=data_FDq1$Estimate+data_FDq1$Std..Error

data.p_FDq1=as.data.frame(cbind(min, med, max))
data.p_FDq1$x=data_FDq1$var
data.p_FDq1$x <- factor(data.p_FDq1$x, levels  = rev(unique(data.p_FDq1$x)))

#### stop and check manually

data.p_FDq1$group <- paste0("group", c(rep(1, 2), rep(2, 2),
                                rep(3, 2), rep(4, 3)
                                ))
data.p_FDq1$group_col <- c(rep("darkseagreen", 2), rep("#78bee5", 2),
                    rep("#e7a40e", 2), rep("lightpink", 3))

data.p_FDq1$p<- ifelse(data_FDq1$Pr...z.. < 0.001, "***",
                ifelse(data_FDq1$Pr...z..< 0.01, "**",
                       ifelse(data_FDq1$Pr...z..< 0.05, "*", "")))

data.p_FDq1$p_col[which(data.p_FDq1$p == "*" & data.p_FDq1$med <= 0)] <- "Negtive effect(P<0.05)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "**" & data.p_FDq1$med <= 0)] <- "Negtive effect(P<0.01)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "***" & data.p_FDq1$med <= 0)] <- "Negtive effect(P<0.001)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "" & data.p_FDq1$med <= 0)] <- "Negtive effect(P>=0.05)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "*" & data.p_FDq1$med >= 0)] <- "Postive effect(P<0.05)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "**" & data.p_FDq1$med >= 0)] <- "Postive effect(P<0.01)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "***" & data.p_FDq1$med >= 0)] <- "Postive effect(P<0.001)"
data.p_FDq1$p_col[which(data.p_FDq1$p == "" & data.p_FDq1$med >= 0)] <- "Postive effect(P>=0.05)"

p_FDq1 <- ggplot(data.p_FDq1)+
  
  geom_hline(yintercept = 0, linewidth = 0.8)+
  
  geom_linerange(aes(x, ymin = min, ymax = max, color = p_col), size=1.0,show.legend = F)+
 
  geom_point(aes(x, med, color = p_col),size=3.0) +
  
  geom_text(aes(x, y = max + 0.05, label = p, color =p_col ),size=5, show.legend = F)+
  
  scale_color_manual(name = "",
                     values = c("Negtive effect(P<0.001)"="dodgerblue4",
                                "Negtive effect(P<0.01)"="steelblue3",
                                "Negtive effect(P<0.05)"= "#7acfff",
                                "Negtive effect(P>=0.05)"="lightblue2",
                                "Postive effect(P<0.001)"="tomato1",
                                "Postive effect(P<0.01)"="orange",
                                "Postive effect(P<0.05)"="#ffbd88",
                                "Postive effect(P>=0.05)"="moccasin"))+
annotate("rect",
           xmin = c(0.4,3.5,5.5,7.5),
           xmax = c(3.5,5.5,7.5,9.6),
           ymin = -0.75, ymax = 0.75, alpha = 0.3, fill = rev(unique(data.p_FDq1$group_col))) +

  scale_y_continuous(expand = c(0,0))+
  xlab("")+
  ylab("Standardized coefficient")+
  labs(title = "FDq1")+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),
        axis.ticks.x = element_line(colour = "black",size = 1),
        axis.ticks.y = element_line(colour = "black",size = 1),
        panel.border = element_rect(color = "black", size = 1.2, fill = NA),
        axis.title.x= element_text(face="bold", color="black",size=12),
        axis.text.x = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12, face = "bold",color = "black"))+
  coord_flip()

plot(p_FDq1)

ggsave("plots_FDq1.pdf", height = 5, width = 6.6)
```

# Extended Fig. 1,4,5,6,7
```{r}
library(GGally)
library(corrplot)
library(ggplot2)
Bio=read.csv("Bio_all.csv",header = T)
ggpairs(Bio[,c(2:8)])+
  theme_bw()

ggsave("Cor00.pdf", height = 7, width = 11)

enm=read.csv("env.csv",head=T)


cols_to_standardize <- 3:46
enm[, cols_to_standardize] <- scale(enm[, cols_to_standardize])


ggpairs(enm[,c(3:11)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "darkseagreen"))
ggsave("Cor01.pdf", height = 7, width = 11)

ggpairs(enm[,c(12:30)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "#88c4e8"))
ggsave("Cor02.pdf", height = 13, width = 13)

ggpairs(enm[,c(31:39)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "#E6E600FF"))
ggsave("Cor03.pdf", height = 7, width = 11)


ggpairs(enm[,c(40:46)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "pink"))
ggsave("Cor04.pdf", height = 7, width = 11)
```

# Extended Fig. 3
```{r}
library(sf)
library(dplyr)
library(rmapshaper)
feow = st_read("feownew.shp")
feow <- st_make_valid(feow)
basin_centers <- st_centroid(valid_shapefile)
result <- st_join(basin_centers, feow, join = st_within)
feow_data=result[which(result$HYBAS_ID %in% data$HYBAS_ID),c(1,21)]
feow_data=as.data.frame(feow_data[,c(1:2)])
#write.csv(feow_data,file="feow_data.csv")

Bio=read.csv("Bio_all.csv",header = T)
Mean_data=merge(feow,Bio[,c(1:3,6:7)],by = "HYBAS_ID")
Mean_data <- subset(Mean_data, !(MHT_TXT %in% c("Large River Deltas", "Oceanic Island")))
Data=Mean_data[,c(2:6)]

result <- Data %>%
  group_by(MHT_TXT) %>%
  summarize(
    mean_TDq0 = mean(TDq0),
    se_TDq0 = sd(TDq0) / sqrt(n()),

    mean_TDq1 = mean(TDq1),
    se_TDq1 = sd(TDq1) / sqrt(n()),

    mean_FDq0 = mean(FDq0),
    se_FDq0 = sd(FDq0) / sqrt(n()),

    mean_FDq1 = mean(FDq1),
    se_FDq1 = sd(FDq1) / sqrt(n()),

  )
write.csv(result,file="Mean_SE.csv")

```

