---
  title: "diversity_global_aquatic_insect"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Standardised
# TD Feature importance
```{r}
setwd(".../input")
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("TDq0", "TDq1", "TDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","FDq0", "FDq1", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq0, TDq1, and TDq2") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c("TDq0" = "darkseagreen", "TDq1" = "#88c4e8", "TDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("TD.pdf", height = 7, width = 7)
```


# FD Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("FDq0", "FDq1", "FDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq1", "TDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$FDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for FDq0, FDq1, and FDq2") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c("FDq0" = "darkseagreen", "FDq1" = "#88c4e8", "FDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("FD.pdf", height = 7, width = 7)
```


# q0 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("TDq0", "FDq0")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq1", "TDq2" ,"FDq1", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq0 and FDq0") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "TDq0" = "#88c4e8", "FDq0" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14,face = "bold"),
    axis.text.y = element_text(size = 14,face = "bold")
  )

ggsave("q0.pdf", height = 10, width = 7)
```


# q1 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("TDq1", "FDq1")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq2" ,"FDq0", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq1 and FDq1") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "TDq1" = "#88c4e8", "FDq1" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("q1.pdf", height = 7, width = 7)
```

# q2 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("TDq2", "FDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq1" ,"FDq0", "FDq1"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq1 and FDq1") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "TDq2" = "#88c4e8", "FDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("q2.pdf", height = 7, width = 7)
```



# Observed
# TD Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("Obs_TDq0", "Obs_TDq1", "Obs_TDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "TDq0", "TDq1", "TDq2","Obs_FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","FDq0", "FDq1", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq0, TDq1, and TDq2") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c("Obs_TDq0" = "darkseagreen", "Obs_TDq1" = "#88c4e8", "Obs_TDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Obs_TD.pdf", height = 7, width = 7)
```


# FD Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("Obs_FDq0", "Obs_FDq1", "Obs_FDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "Obs_TDq2","FDq0","FDq1", "FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq1", "TDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$FDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for FDq0, FDq1, and FDq2") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c("Obs_FDq0" = "darkseagreen", "Obs_FDq1" = "#88c4e8", "Obs_FDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Obs_FD.pdf", height = 7, width = 7)
```


# q0 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("Obs_TDq0", "Obs_FDq0")
feature_columns <- setdiff(names(new_df), c(target_columns, "TDq0", "Obs_TDq1", "Obs_TDq2","FDq0","Obs_FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq1", "TDq2" ,"FDq1", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq0 and FDq0") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "Obs_TDq0" = "#88c4e8", "Obs_FDq0" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Obs_q0.pdf", height = 7, width = 7)
```


# q1 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("Obs_TDq1", "Obs_FDq1")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "TDq1", "Obs_TDq2","Obs_FDq0","FDq1", "Obs_FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq2" ,"FDq0", "FDq2"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq1 and FDq1") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "Obs_TDq1" = "#88c4e8", "Obs_FDq1" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Obs_q1.pdf", height = 7, width = 7)
```

# q2 Feature importance
```{r}
# Load necessary packages
library(randomForest)
library(ggplot2)
library(caret)

# Read data
new_df <- read.csv("test.csv")

# Define target and feature columns
target_columns <- c("Obs_TDq2", "Obs_FDq2")
feature_columns <- setdiff(names(new_df), c(target_columns, "Obs_TDq0", "Obs_TDq1", "TDq2","Obs_FDq0","Obs_FDq1", "FDq2","Sam_eff", "HYBAS_ID","TDq0", "TDq1" ,"FDq0", "FDq1"))

# Initialize a dataframe to store feature importance
importance_df <- data.frame()

# Data partitioning
set.seed(42)
trainIndex <- createDataPartition(new_df$TDq0, p = .8, list = FALSE)
trainData <- new_df[trainIndex, ]
testData <- new_df[-trainIndex, ]

# Train models and extract feature importance
for (target in target_columns) {
  model <- randomForest(trainData[, feature_columns], trainData[, target], random_state=42)
  importance <- importance(model)
  importance_data <- data.frame(Feature = rownames(importance), Importance = importance[, 1], Target = target)
  
  # Normalize importance values to be between 0 and 1
  importance_data$Importance <- importance_data$Importance / max(importance_data$Importance)
  
  importance_df <- rbind(importance_df, importance_data)
}

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Target)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Feature Importance for TDq1 and FDq1") +
  xlab("Feature") +
  ylab("Importance") +
  theme_minimal() +
  scale_fill_manual(values = c( "Obs_TDq2" = "#88c4e8", "Obs_FDq2" = "#ffbd88")) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Obs_q2.pdf", height = 7, width = 7)
```
