---
  title: "Qiantang river metacommunity-Macroinvertebrates"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1.0 Import data
```{r}
#setwd("E:/.../input_data")
library(dplyr) # data manipulation
library(tidyverse)# data manipulation
library(vegan) # ordination methods
library(lubridate)# year, month function
library(data.table)
library(BAT)
library(betapart)
library(data.table)

### Reading of data and initial selection
EPTO=fread("Global_EPTO_Database.csv")
EPTO.s<- filter(EPTO,!duplicated(EPTO$occurrence_ID))


### Elimination of records that do not correspond to actual sites
EPTO.s1=EPTO.s[which(cen_fl != "1"& EPTO.s$cap_fl !="1"  & EPTO.s$snapped !="1"),c(5,8,9,14:16)]

#same_values_rows <- duplicated(EPTO.s1) | duplicated(EPTO.s1, fromLast = TRUE)
#EPTO.s1 <- subset(EPTO.s1, !same_values_rows)
####Delete 
EPTO.s1 <- EPTO.s1[!duplicated(EPTO.s1), ]


### Assign unique IDs to sites with consistent latitude and longitude
n <- nrow(EPTO.s1)
EPTO.s1$record_num <- 1:n
EPTO.s1$unique=EPTO.s1$longitude+EPTO.s1$latitude
EPTO.s1$site_ID <- NA
EPTO.s1 <- EPTO.s1 %>% mutate(site_ID = as.numeric(factor(unique)))

#s1=EPTO.s1[c(1:1000000),c(2,3,7)]
#s2=EPTO.s1[c(1000001:2000000),c(2,3,7)]
#s3=EPTO.s1[c(2000001:3000000),c(2,3,7)]
#s4=EPTO.s1[c(3000001:4000000),c(2,3,7)]
#s5=EPTO.s1[c(4000001:5000000),c(2,3,7)]
#s6=EPTO.s1[c(5000001:6000000),c(2,3,7)]
#s7=EPTO.s1[c(6000001:6778667),c(2,3,7)]

#write.csv(s1,file= "s1.csv")
#write.csv(s2,file= "s2.csv")
#write.csv(s3,file= "s3.csv")
#write.csv(s4,file= "s4.csv")
#write.csv(s5,file= "s5.csv")
#write.csv(s6,file= "s6.csv")
#write.csv(s7,file= "s7.csv")


### Connect to HYBAS_ID (i.e.Basin ID)
loc_01=read.csv("site001.csv")
loc_02=read.csv("site002.csv")
loc_03=read.csv("site003.csv")
loc_04=read.csv("site004.csv")
loc_05=read.csv("site005.csv")
loc_06=read.csv("site006.csv")
loc_07=read.csv("site007.csv")
loc_all=rbind(loc_01, loc_02, loc_03,loc_04, loc_05, loc_06,loc_07)
merged_data <- merge(EPTO.s1, loc_all, by = "record_num")
Data.o=merged_data[,c(2:7,9,12)]

### Deletion of basins with only one genus
Data.s=Data.o %>% group_by(HYBAS_ID) %>% filter(n() >1)

### Deletion of one basin have only one site
Data.s1 <- Data.s %>%
  group_by(HYBAS_ID) %>%
  filter(n_distinct(site_ID) > 1) %>%
  ungroup()

### Deletion of sites with only one genus
Data=Data.s1 %>% group_by(site_ID) %>% filter(n() >1)

```

#2.0 All Basin
```{r}
#all_ID=unique(Data$HYBAS_ID)
#all_ID=data.frame(all_ID)
#write.csv(all_ID,file = "all_ID.csv")

all_ID=read.csv("all_ID.csv",header = T)
Basin_ID=all_ID$all_ID
data.i <- NULL

for (i in Basin_ID) {
  tryCatch({
    spm = Data[Data$HYBAS_ID == i, ]
    spm$Occ = rep("1")
    spm_n = dcast(spm, site_ID + longitude.x + latitude.x + year + month + sampling_day ~ genus)
    spm_n[is.na(spm_n)] = 0
    spm.o=spm_n[,-c(2:7)]
    spm.o <- mutate_at(spm.o, vars(2:last_col()), as.numeric)
    sums <- colSums(spm.o[, -1])
    new_col_names <- names(spm.o)[2:ncol(spm.o)]
    spm_all=data.frame(sums)
    df<- rownames_to_column(spm_all, var = "new_column_name")
    colnames(df)[2] <- as.character(i)  
    if (is.null(data.i)) {
      data.i <- df
    } else {
      data.i <- merge(data.i, df, by.x = "new_column_name", by.y = "new_column_name", all.x = TRUE, all.y = TRUE)
    }
  }, error = function(e) {
    cat("Error occurred for i =", i, "\n")
  })
}

data.i[is.na(data.i)] <- 0
write.csv(data.i,file = "all_abu.csv")



```



#3.0 WSB "well-sampled basin"
```{r}
irregular_data=unique(Data$HYBAS_ID)

data.i <- NULL

for (i in irregular_data) {
  tryCatch({
    spm = Data[Data$HYBAS_ID == "1040015030", ]
    spm$Occ = rep("1")
    spm_n = dcast(spm, site_ID + longitude.x + latitude.x + year + month + sampling_day ~ genus)
    spm_n[is.na(spm_n)] = 0
    spm.o=spm_n[,-c(2:6)]
    spm.o <- mutate_at(spm.o, vars(2:last_col()), as.numeric)
      if (ncol(spm.o) >= 11) {
  spm.o <- spm.o
} else {
  stop("Error:  less than 5 taxon.")
}
    spm.s1 <- spm.o %>%
  select(site_ID, everything()) %>% 
  group_by(site_ID) %>%
  summarise(across(everything(), sum))
    
sum_cols<- sum(spm.s1[, 2:ncol(spm.s1)])

     if (sum_cols/nrow(spm.s1) >= 2 & nrow(spm.s1) >= 10 ) {
  spm.s1 <- spm.s1
} else {
  stop("Error: abundance/site less than 2 or less than 5 sites")
}
    ID <- data.frame(i)
    data.i <- rbind(data.i,ID)
  }, error = function(e) {
    cat("Error occurred for i =", i, "\n")
  })
}

write.csv(data.i,file="Basin_ID.csv")

```


#4.0 Global abundances data
```{r}
basin_ID=read.csv("Basin_ID.csv",header = T)

Basin_ID=unique(basin_ID$i)

data.i <- NULL

for (i in Basin_ID) {
  tryCatch({
    spm = Data[Data$HYBAS_ID == i, ]
    spm$Occ = rep("1")
    spm_n = dcast(spm, site_ID + longitude.x + latitude.x + year + month + sampling_day ~ genus)
    spm_n[is.na(spm_n)] = 0
    spm.o=spm_n[,-c(2:7)]
    spm.o <- mutate_at(spm.o, vars(2:last_col()), as.numeric)
    sums <- colSums(spm.o[, -1])
    new_col_names <- names(spm.o)[2:ncol(spm.o)]
    spm_all=data.frame(sums)
    df<- rownames_to_column(spm_all, var = "new_column_name")
    colnames(df)[2] <- as.character(i)  
    if (is.null(data.i)) {
      data.i <- df
    } else {
      data.i <- merge(data.i, df, by.x = "new_column_name", by.y = "new_column_name", all.x = TRUE, all.y = TRUE)
    }
  }, error = function(e) {
    cat("Error occurred for i =", i, "\n")
  })
}

data.i[is.na(data.i)] <- 0
write.csv(data.i,file = "Abundances.csv")

```


#5.0 Hill Diversity calculation
```{r}
library(devtools)
library(iNEXT)
library(iNEXT.3D)

abu=read.csv("Abundances.csv",header = T,row.names = 1,check.names = FALSE)

a=apply(abu, 2, function(x) iNEXT.3D:::Coverage(x, 'abundance', sum(x))) 
mid=median(a)
view(mid)
view(a)

####################################
#TD mid  nboot need 50
TD_est=estimate3D(data = abu, diversity = 'TD', q = c(0,1), datatype = 'abundance', base = 'coverage', level = c(mid), nboot = 50)

SE_data=TD_est[(TD_est$Order.q=="0"),c(1,5,7)]
max_se=max(SE_data$s.e.)

#count <- sum(TD_est$Method == "Rarefaction")

###### nboot need50
TD_iNEXT=iNEXT3D(abu, diversity = "TD", q = c(0, 1), datatype = "abundance", nboot = 50)
TD_ast=TD_iNEXT$TDAsyEst

#############
#proportion
TD_q1_mid=TD_est[(TD_est$Order.q=="1"& TD_est$SC==mid),c(1,5)]
TD_q1_ast=TD_ast[(TD_ast$`Taxonomic Diversity`=="Shannon diversity"),c(1,3)]
TD_Proportion=merge(TD_q1_mid, TD_q1_ast, by = "Assemblage")
TD_Proportion$Proportion <- TD_Proportion$`Taxonomic Observed` / TD_Proportion$qTD

TD_q1_mid=TD_est[(TD_est$Order.q=="0"& TD_est$SC==mid),c(1,5)]
TD_q1_ast=TD_ast[(TD_ast$`Taxonomic Diversity`=="Species richness"),c(1,3)]
TD_Proportion=merge(TD_q1_mid, TD_q1_ast, by = "Assemblage")
TD_Proportion$Proportion <- TD_Proportion$`Taxonomic Observed` / TD_Proportion$qTD
count <- sum(TD_Proportion$Proportion > 1)
#write.csv(TD_Proportion,file="pro.csv")


TD_pre=TD_iNEXT$TDAsyEst
TD_pre_pro=TD_pre[(TD_pre$`Taxonomic Diversity`=="Species richness"),c(1,3,4)]
TD_pre_pro$Proportion <- TD_pre_pro$`Taxonomic Observed` / TD_pre_pro$`Taxonomic Estimator`

write.csv(TD_est,file = "TD_est_mid.csv")
write.csv(TD_ast,file = "TD_ast.csv")
write.csv(TD_Proportion,file = "TD_Proportion.csv")

###################################
#FD
library(FD)
ex1 <- gowdis(dummy$trait)
traits <- read.csv("Trait.csv", row.names = 1, header= TRUE)

distM <- cluster::daisy(x = traits, metric = "gower") %>% as.matrix()

FD_est <- estimate3D(data = abu, diversity = 'FD', q = c(0, 1), datatype = 'abundance', base = 'coverage',level = c(mid), nboot = 50, FDdistM = distM)


write.csv(FD_est,file = "FD_est_mid.csv")
```


#6.0 Hill all basin
```{r}
library(devtools)
library(iNEXT)
library(iNEXT.3D)

abu2=read.csv("all_abu.csv",header = T,row.names = 1,check.names = FALSE)

a2=apply(abu, 2, function(x) iNEXT.3D:::Coverage(x, 'abundance', sum(x))) 
mid2=median(a2)
####################################


#################  find max_se
TD_est=estimate3D(data = abu, diversity = 'TD', q = c(0,1), datatype = 'abundance', base = 'coverage', level = c(mid), nboot = 50)
SE_data=TD_est[(TD_est$Order.q=="0"),c(1,5,7)]
max_se=max(SE_data$s.e.)
#################


#TD mid  nboot need 50
TD_all_est=estimate3D(data = abu2, diversity = 'TD', q = c(0,1), datatype = 'abundance', base = 'coverage', level = c(mid2), nboot = 50)

gap_Basin=TD_all_est[(TD_all_est$Order.q=="0" & TD_all_est$s.e. < max_se),c(1,5,7)]


###### no need50
all_TD_iNEXT=iNEXT3D(abu2, diversity = "TD", q = c(0, 1), datatype = "abundance", nboot = 50)
all_TD_ast=all_TD_iNEXT$TDAsyEst

#############
gap_TD_ast=all_TD_ast[which(all_TD_ast$`Taxonomic Diversity` =="Species richness" &  all_TD_ast$Assemblage %in% gap_Basin$Assemblage),]


#proportion
all_TD_q1_mid=TD_all_est[(TD_est$Order.q=="0"& TD_est$SC==mid ),c(1,5)]
pro=all_TD_q1_mid[which(all_TD_q1_mid$Assemblage %in% gap_TD_ast$Assemblage ),]
pro_merge=merge(gap_TD_ast,pro, by="Assemblage")
pro_merge$proportion=pro_merge$`Taxonomic Observed`/pro_merge$qTD
count <- sum(pro_merge$proportion > 1)

write.csv(pro_merge,file="mid2_01.csv")

```


#7.0 Observed TD FD
```{r}
library(vegan)
abu=read.csv("Abundances.csv",header = T,row.names = 1,check.names = FALSE)
spm=t(abu)

SR=specnumber(spm)
SR=data.frame(SR)

shannon=diversity(spm,index = "shannon")
SH=data.frame(shannon)

TD_observe=data.frame(SR,SH)

traits <- read.csv("Trait.csv",  header= TRUE)
trm.s=traits[which(traits$genus %in% colnames(spm)),]

row.names(trm.s) <- trm.s$genus
trm.s <- trm.s[, -1]

library(FD)
FD <- dbFD(trm.s, spm)

FD_reslut=data.frame(FD$FRic,FD$FEve,FD$FDiv,FD$FDis,FD$RaoQ)

write.csv(FD_reslut,file = "FD_reslut.csv")


FD_observe=read.csv("FD_reslut.csv",header = T)
obesrve=data.frame(TD_observe,FD_observe)
#####   MergeBio
TD_est=read.csv("TD_est_mid.csv")
TDq0=TD_est[(TD_est$Order.q=="0"),c(2,6)]
TDq1=TD_est[(TD_est$Order.q=="1"),c(2,6)]

FD_est=read.csv("FD_est_mid.csv")
FDq0=FD_est[(FD_est$Order.q=="0"),c(2,6)]
FDq1=FD_est[(FD_est$Order.q=="1"),c(2,6)]

merged1 <- merge(TDq0, TDq1, by = "Assemblage", all = TRUE)
merged2 <- merge(merged1, FDq0, by = "Assemblage", all = TRUE)
merged3 <- merge(merged2, FDq1, by = "Assemblage", all = TRUE)

colnames(merged3)[1] <- "HYBAS_ID"
colnames(merged3)[2] <- "TDq0"
colnames(merged3)[3] <- "TDq1"
colnames(merged3)[4] <- "FDq0"
colnames(merged3)[5] <- "FDq1"

Proportion=read.csv("TD_proportion.csv",header = T)
por=Proportion[,c(2,4,5)]
colnames(por)[1] <- "HYBAS_ID"

obesrve$HYBAS_ID <- rownames(obesrve)
obesrve <- obesrve[, c("HYBAS_ID", names(obesrve)[-ncol(obesrve)])]

TDFD=merge(merged3,por, by = "HYBAS_ID", all = TRUE)
Bio=merge(TDFD,obesrve, by = "HYBAS_ID", all = TRUE)

write.csv(Bio,file="Bio_all.csv")
```

#8.0 site num/ sam_eff
```{r}
#hybas_id_counts <- table(loc_all$HYBAS_ID)
#site_num <- as.data.frame(hybas_id_counts)
#colnames(site_num) <- c("HYBAS_ID", "Site_num")
#enm<- merge(enm, site_num, by = "HYBAS_ID")
#enm$Sam_eff <- (enm$Site_num / enm$Area)*1000000
#write.csv(enm,file = "enm_new.csv")

enm=read.csv("env.csv",header = T)
df=Data[,c(7:8)]
result <- df %>%
  group_by(HYBAS_ID) %>%
  summarize(num = n_distinct(site_ID))

site_num=result[which(result$HYBAS_ID %in% enm$HYBAS_ID),]
enm=merge(enm,site_num, by = "HYBAS_ID")
#num=enm[,c(1,47)]
#write.csv(num,file = "num.csv")

enm$Sam_eff <- (enm$num / enm$Area)*1000000
write.csv(enm,file = "env318.csv")


```


#9.0 Corplot
```{r}
library(GGally)
library(corrplot)
library(ggplot2)
Bio=read.csv("Bio_all.csv",header = T)
ggpairs(Bio[,c(2:8)])+
  theme_bw()

#OLD=read.csv("OLD.csv",header = T)
#old=OLD[which(OLD$HYBAS_ID  %in% basin_ID$i),]
#NEW=read.csv("NEW.csv",header = T)
#new=NEW[which(NEW$HYBAS_ID  %in% basin_ID$i),]
#merge=merge(old,new,by="HYBAS_ID")
#write.csv(merge,file="env318.csv")

ggsave("Cor00.pdf", height = 7, width = 11)


enm=read.csv("env.csv",head=T)


cols_to_standardize <- 3:46
enm[, cols_to_standardize] <- scale(enm[, cols_to_standardize])


ggpairs(enm[,c(3:11)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "darkseagreen"))
ggsave("Cor01.pdf", height = 7, width = 11)

ggpairs(enm[,c(12:30)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "#88c4e8"))
ggsave("Cor02.pdf", height = 13, width = 13)

ggpairs(enm[,c(31:39)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "#E6E600FF"))
ggsave("Cor03.pdf", height = 7, width = 11)


ggpairs(enm[,c(40:46)])+
  theme_bw()+
  theme(strip.background = element_rect(fill = "pink"))
ggsave("Cor04.pdf", height = 7, width = 11)
```


#10.0 VPA
```{r}
library(vegan)
library(ggvenn)
enm=read.csv("env.csv",head=T)
merged_diversity=read.csv("Bio_all.csv",header = T)

colnames(merged_diversity)[1] <- "HYBAS_ID"
data <- merge(merged_diversity, enm, by= "HYBAS_ID")
enm.hy=data[,c(12:14,17,19)]
enm.cl=data[,c(21,22,28,32,35)]
enm.ge=data[,c(40,42,44:46)]
enm.an=data[,c(49:53)]


par(mfrow=c(2,2))
vpa.TDq0_mid=varpart(data[,2],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.TDq0_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

#####  TDq1 mid
vpa.TDq1_mid=varpart(data[,3],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.TDq1_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))


#################### FD
#####  FDq0 mid
vpa.FDq0_mid=varpart(data[,6],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.FDq0_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

#####  FDq1 mid
vpa.FDq1_mid=varpart(data[,7],enm.hy,enm.cl,enm.ge,enm.an)
plot(vpa.FDq1_mid,Xnames=c("Hydrology", "Climate","Geomorphological","Anthropogenic"),
     bg = c("darkseagreen","#78bee5","#e7a40e","lightpink"))

colnames(enm.hy)
colnames(enm.cl)
colnames(enm.ge)
colnames(enm.an)

```


#11.0 Latitude pattern
```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(corrr)
library(tmap)
library(spdep)
library(tigris)
library(rmapshaper)
library(flextable)
library(car)
library(spatialreg)
library(stargazer)
library(spatialreg)
library(spdep)
#install.packages("gcookbook")
#install.packages("ggplot2")
#install.packages("ggthemes")
library(gcookbook)
library(ggplot2)
library(ggthemes)

shp=st_read("Global basin.shp")
valid_shapefile <- st_make_valid(shp)
basins_boundaries <- st_geometry(valid_shapefile)
basins_centroids <- st_centroid(basins_boundaries)
valid_shapefile$average_latitude <- st_coordinates(basins_centroids)[, 2]
latitude=valid_shapefile[which(valid_shapefile$HYBAS_ID %in% data$HYBAS_ID), c(1,17)]
latitude=as.data.frame(latitude[,c(1:2)])
colnames(data)[1] <- "HYBAS_ID"
latitude_data=merge(data, latitude,  by = "HYBAS_ID")
L_data=latitude_data[,c(1:3,6,7,56)]


#TDq0

ggplot(L_data, aes(x = average_latitude, y = TDq0)) +
  geom_point(color = "#7acfff", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "steelblue3", fill = "skyblue") +
  labs(x = "average_latitude", y = "TDq0", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_TDq0new.pdf", height = 4, width = 7)

#TDq1

ggplot(L_data, aes(x = average_latitude, y = TDq1)) +
  geom_point(color = "#7acfff", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "steelblue3", fill = "skyblue") +
  labs(x = "average_latitude", y = "TDq1", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_TDq1new.pdf", height = 4, width = 7)

#FDq0

ggplot(L_data, aes(x = average_latitude, y = FDq0)) +
  geom_point( color = "orange", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "tomato1",fill="#ffbd88")+
  labs(x = "average_latitude", y = "FDq0", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_FDq0new.pdf", height = 4, width = 7)

#FDq1

ggplot(L_data, aes(x = average_latitude, y = FDq1)) +
  geom_point( color = "orange", size = 2) +
  stat_smooth(method = "loess", formula = y ~ x, span = 0.5, color = "tomato1",fill="#ffbd88")+
  labs(x = "average_latitude", y = "FDq1", title = "Scatterplot", caption = "Source: gcookbook") +
  theme_few() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16))

ggsave("L_FDq1new.pdf", height = 4, width = 7)
```

# 12.0 mean +- se
```{r}
Bio=read.csv("Bio_all.csv",header = T)
Mean_data=merge(feow,Bio[,c(1:3,6:7)],by = "HYBAS_ID")
Mean_data <- subset(Mean_data, !(MHT_TXT %in% c("Large River Deltas", "Oceanic Island")))
Data=Mean_data[,c(2:6)]

result <- Data %>%
  group_by(MHT_TXT) %>%
  summarize(
    mean_TDq0 = mean(TDq0),
    se_TDq0 = sd(TDq0) / sqrt(n()),

    mean_TDq1 = mean(TDq1),
    se_TDq1 = sd(TDq1) / sqrt(n()),

    mean_FDq0 = mean(FDq0),
    se_FDq0 = sd(FDq0) / sqrt(n()),

    mean_FDq1 = mean(FDq1),
    se_FDq1 = sd(FDq1) / sqrt(n()),

  )
write.csv(result,file="Mean_SE.csv")
```


#13.0 FEWO
```{r}
library(sf)
library(dplyr)
library(rmapshaper)
feow = st_read("feownew.shp")
feow <- st_make_valid(feow)

basin_centers <- st_centroid(valid_shapefile)
result <- st_join(basin_centers, feow, join = st_within)
feow_data=result[which( result$HYBAS_ID %in% data$HYBAS_ID),c(1,21)]
feow_data=as.data.frame(feow_data[,c(1:2)])
#write.csv(feow_data,file="feow_data.csv")

############ New start

```


#14.0 Box plot
```{r}
feow=read.csv("feow_data.csv",header = T)

unique=unique(feow$MHT_TXT)
value_counts <- table(feow$MHT_TXT)
unique_num=data.frame(unique,value_counts)

Box_data=merge(feow,data[,c(1:3,6,7)],by = "HYBAS_ID")
Box_data <- subset(Box_data, !(MHT_TXT %in% c("Large River Deltas", "Oceanic Island")))

library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggsignif)
library(rstatix)

TSCR=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Coastal Rivers"),]
TSF=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Floodplain Rivers and Wetland Complexes"),]
TUR=Box_data[which(Box_data$MHT_TXT=="Temperate Upland Rivers"),]
MF=Box_data[which(Box_data$MHT_TXT=="Montane Freshwaters"),]
TCR=Box_data[which(Box_data$MHT_TXT=="Temperate Coastal Rivers"),]
XF=Box_data[which(Box_data$MHT_TXT=="Xeric Freshwaters and Endorheic Basins"),]
TSUR=Box_data[which(Box_data$MHT_TXT=="Tropical and Subtropical Upland Rivers"),]
LL=Box_data[which(Box_data$MHT_TXT=="Large Lakes"),]
TFR=Box_data[which(Box_data$MHT_TXT=="Temperate Floodplain Rivers and Wetlands"),]
PF=Box_data[which(Box_data$MHT_TXT=="Polar Freshwaters"),]
```


#14.1 TDq0
```{r}
data_TSCR_TDq0=TSCR$TDq0
data_TSF_TDq0=TSF$TDq0
data_TUR_TDq0=TUR$TDq0
data_MF_TDq0=MF$TDq0
data_TCR_TDq0=TCR$TDq0
data_XF_TDq0=XF$TDq0
data_TSUR_TDq0=TSUR$TDq0
data_LL_TDq0=LL$TDq0
data_TFR_TDq0=TFR$TDq0
data_PF_TDq0=PF$TDq0


max_length_TDq0=max(length(data_TSCR_TDq0),length(data_TSF_TDq0),length(data_TUR_TDq0),
                    length(data_MF_TDq0),length(data_TCR_TDq0),length(data_XF_TDq0),
                    length(data_TSUR_TDq0),length(data_LL_TDq0),length(data_TFR_TDq0),
                    length(data_PF_TDq0))

data_TSCR_TDq0_padded <- c(data_TSCR_TDq0, rep(NA, max_length_TDq0 - length(data_TSCR_TDq0)))
data_TSF_TDq0_padded <- c(data_TSF_TDq0, rep(NA, max_length_TDq0 - length(data_TSF_TDq0)))
data_TUR_TDq0_padded <- c(data_TUR_TDq0, rep(NA, max_length_TDq0 - length(data_TUR_TDq0)))
data_MF_TDq0_padded <- c(data_MF_TDq0, rep(NA, max_length_TDq0 - length(data_MF_TDq0)))
data_TCR_TDq0_padded <- c(data_TCR_TDq0, rep(NA, max_length_TDq0 - length(data_TCR_TDq0)))
data_XF_TDq0_padded <- c(data_XF_TDq0, rep(NA, max_length_TDq0 - length(data_XF_TDq0)))
data_TSUR_TDq0_padded <- c(data_TSUR_TDq0, rep(NA, max_length_TDq0 - length(data_TSUR_TDq0)))
data_LL_TDq0_padded <- c(data_LL_TDq0, rep(NA, max_length_TDq0 - length(data_LL_TDq0)))
data_TFR_TDq0_padded <- c(data_TFR_TDq0, rep(NA, max_length_TDq0 - length(data_TFR_TDq0)))
data_PF_TDq0_padded <- c(data_PF_TDq0, rep(NA, max_length_TDq0 - length(data_PF_TDq0)))


TDq0_DATA <- data.frame(TSCR=data_TSCR_TDq0_padded,
                        TSF=data_TSF_TDq0_padded,
                        TUR=data_TUR_TDq0_padded,
                        MF=data_MF_TDq0_padded,
                        TCR=data_TCR_TDq0_padded,
                        XF=data_XF_TDq0_padded,
                        TSUR=data_TSUR_TDq0_padded,
                        LL=data_LL_TDq0_padded,
                        TFR=data_TFR_TDq0_padded,
                        PF=data_PF_TDq0_padded)

Box_TDq0 <-Box_data[,c(2,3)] 
Box_TDq0$MHT_TXT <- factor(Box_TDq0$MHT_TXT )

stat.test <- Box_TDq0 %>%
  mutate(TDq0 = as.numeric(as.character(TDq0))) %>%
  wilcox_test(
    TDq0 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_TDq0)+
  # 箱线图：
  geom_boxplot(aes(MHT_TXT, TDq0, color= MHT_TXT))+
  
  # 颜色模式：
  scale_color_manual(values = colors)+
  xlab("")+
  # 主题：
  theme_classic()+
  labs(title = "TDq0")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

TDq0_DATA_no_na <- replace(TDq0_DATA, is.na(TDq0_DATA), -Inf)

y_value <- rep(apply(TDq0_DATA_no_na, 2, max)[1:9], 9:1) + 0

y_value <- y_value + c(3*1:9, 3*1:8, 3*1:7, 3*1:6,3*1:5, 3*1:4, 3*1:3, 3*1:2, 3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("TDq0.pdf", height = 6, width = 7)
```

#14.2 TDq1
```{r}
data_TSCR_TDq1=TSCR$TDq1
data_TSF_TDq1=TSF$TDq1
data_TUR_TDq1=TUR$TDq1
data_MF_TDq1=MF$TDq1
data_TCR_TDq1=TCR$TDq1
data_XF_TDq1=XF$TDq1
data_TSUR_TDq1=TSUR$TDq1
data_LL_TDq1=LL$TDq1
data_TFR_TDq1=TFR$TDq1
data_PF_TDq1=PF$TDq1


max_length_TDq1=max(length(data_TSCR_TDq1),length(data_TSF_TDq1),length(data_TUR_TDq1),
                    length(data_MF_TDq1),length(data_TCR_TDq1),length(data_XF_TDq1),
                    length(data_TSUR_TDq1),length(data_LL_TDq1),length(data_TFR_TDq1),
                    length(data_PF_TDq1))

data_TSCR_TDq1_padded <- c(data_TSCR_TDq1, rep(NA, max_length_TDq1 - length(data_TSCR_TDq1)))
data_TSF_TDq1_padded <- c(data_TSF_TDq1, rep(NA, max_length_TDq1 - length(data_TSF_TDq1)))
data_TUR_TDq1_padded <- c(data_TUR_TDq1, rep(NA, max_length_TDq1 - length(data_TUR_TDq1)))
data_MF_TDq1_padded <- c(data_MF_TDq1, rep(NA, max_length_TDq1 - length(data_MF_TDq1)))
data_TCR_TDq1_padded <- c(data_TCR_TDq1, rep(NA, max_length_TDq1 - length(data_TCR_TDq1)))
data_XF_TDq1_padded <- c(data_XF_TDq1, rep(NA, max_length_TDq1 - length(data_XF_TDq1)))
data_TSUR_TDq1_padded <- c(data_TSUR_TDq1, rep(NA, max_length_TDq1 - length(data_TSUR_TDq1)))
data_LL_TDq1_padded <- c(data_LL_TDq1, rep(NA, max_length_TDq1 - length(data_LL_TDq1)))
data_TFR_TDq1_padded <- c(data_TFR_TDq1, rep(NA, max_length_TDq1 - length(data_TFR_TDq1)))
data_PF_TDq1_padded <- c(data_PF_TDq1, rep(NA, max_length_TDq1 - length(data_PF_TDq1)))


TDq1_DATA <- data.frame(TSCR=data_TSCR_TDq1_padded,
                        TSF=data_TSF_TDq1_padded,
                        TUR=data_TUR_TDq1_padded,
                        MF=data_MF_TDq1_padded,
                        TCR=data_TCR_TDq1_padded,
                        XF=data_XF_TDq1_padded,
                        TSUR=data_TSUR_TDq1_padded,
                        LL=data_LL_TDq1_padded,
                        TFR=data_TFR_TDq1_padded,
                        PF=data_PF_TDq1_padded)

Box_TDq1 <-Box_data[,c(2,4)] 
Box_TDq1$MHT_TXT <- factor(Box_TDq1$MHT_TXT )

stat.test <- Box_TDq1 %>%
  mutate(TDq1 = as.numeric(as.character(TDq1))) %>%
  wilcox_test(
    TDq1 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_TDq1)+
  # 箱线图：
  geom_boxplot(aes(MHT_TXT, TDq1, color= MHT_TXT))+
  
  # 颜色模式：
  scale_color_manual(values = colors)+
  xlab("")+
  # 主题：
  theme_classic()+
  labs(title = "TDq1")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

TDq1_DATA_no_na <- replace(TDq1_DATA, is.na(TDq1_DATA), -Inf)

y_value <- rep(apply(TDq1_DATA_no_na, 2, max)[1:9], 9:1) + 0

y_value <- y_value + c(3*1:9, 3*1:8, 3*1:7, 3*1:6,3*1:5, 3*1:4, 3*1:3, 3*1:2, 3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("TDq1.pdf", height = 6, width = 7)
```

#14.3 FDq0
```{r}
data_TSCR_FDq0=TSCR$FDq0
data_TSF_FDq0=TSF$FDq0
data_TUR_FDq0=TUR$FDq0
data_MF_FDq0=MF$FDq0
data_TCR_FDq0=TCR$FDq0
data_XF_FDq0=XF$FDq0
data_TSUR_FDq0=TSUR$FDq0
data_LL_FDq0=LL$FDq0
data_TFR_FDq0=TFR$FDq0
data_PF_FDq0=PF$FDq0


max_length_FDq0=max(length(data_TSCR_FDq0),length(data_TSF_FDq0),length(data_TUR_FDq0),
                    length(data_MF_FDq0),length(data_TCR_FDq0),length(data_XF_FDq0),
                    length(data_TSUR_FDq0),length(data_LL_FDq0),length(data_TFR_FDq0),
                    length(data_PF_FDq0))

data_TSCR_FDq0_padded <- c(data_TSCR_FDq0, rep(NA, max_length_FDq0 - length(data_TSCR_FDq0)))
data_TSF_FDq0_padded <- c(data_TSF_FDq0, rep(NA, max_length_FDq0 - length(data_TSF_FDq0)))
data_TUR_FDq0_padded <- c(data_TUR_FDq0, rep(NA, max_length_FDq0 - length(data_TUR_FDq0)))
data_MF_FDq0_padded <- c(data_MF_FDq0, rep(NA, max_length_FDq0 - length(data_MF_FDq0)))
data_TCR_FDq0_padded <- c(data_TCR_FDq0, rep(NA, max_length_FDq0 - length(data_TCR_FDq0)))
data_XF_FDq0_padded <- c(data_XF_FDq0, rep(NA, max_length_FDq0 - length(data_XF_FDq0)))
data_TSUR_FDq0_padded <- c(data_TSUR_FDq0, rep(NA, max_length_FDq0 - length(data_TSUR_FDq0)))
data_LL_FDq0_padded <- c(data_LL_FDq0, rep(NA, max_length_FDq0 - length(data_LL_FDq0)))
data_TFR_FDq0_padded <- c(data_TFR_FDq0, rep(NA, max_length_FDq0 - length(data_TFR_FDq0)))
data_PF_FDq0_padded <- c(data_PF_FDq0, rep(NA, max_length_FDq0 - length(data_PF_FDq0)))


FDq0_DATA <- data.frame(TSCR=data_TSCR_FDq0_padded,
                        TSF=data_TSF_FDq0_padded,
                        TUR=data_TUR_FDq0_padded,
                        MF=data_MF_FDq0_padded,
                        TCR=data_TCR_FDq0_padded,
                        XF=data_XF_FDq0_padded,
                        TSUR=data_TSUR_FDq0_padded,
                        LL=data_LL_FDq0_padded,
                        TFR=data_TFR_FDq0_padded,
                        PF=data_PF_FDq0_padded)

Box_FDq0 <-Box_data[,c(2,5)] 
Box_FDq0$MHT_TXT <- factor(Box_FDq0$MHT_TXT )

stat.test <- Box_FDq0 %>%
  mutate(FDq0 = as.numeric(as.character(FDq0))) %>%
  wilcox_test(
    FDq0 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_FDq0)+
  # 箱线图：
  geom_boxplot(aes(MHT_TXT, FDq0, color= MHT_TXT))+
  
  # 颜色模式：
  scale_color_manual(values = colors)+
  xlab("")+
  # 主题：
  theme_classic()+
  labs(title = "FDq0")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

FDq0_DATA_no_na <- replace(FDq0_DATA, is.na(FDq0_DATA), -Inf)

y_value <- rep(apply(FDq0_DATA_no_na, 2, max)[1:9], 9:1) + 2

y_value <- y_value + c(0.5*1:9, 0.5*1:8, 0.5*1:7, 0.5*1:6,0.5*1:5, 0.5*1:4, 0.5*1:1, 0.5*1:2, 0.5)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("FDq0.pdf", height = 6, width = 7)
```

#14.4 FDq1
```{r}
data_TSCR_FDq1=TSCR$FDq1
data_TSF_FDq1=TSF$FDq1
data_TUR_FDq1=TUR$FDq1
data_MF_FDq1=MF$FDq1
data_TCR_FDq1=TCR$FDq1
data_XF_FDq1=XF$FDq1
data_TSUR_FDq1=TSUR$FDq1
data_LL_FDq1=LL$FDq1
data_TFR_FDq1=TFR$FDq1
data_PF_FDq1=PF$FDq1


max_length_FDq1=max(length(data_TSCR_FDq1),length(data_TSF_FDq1),length(data_TUR_FDq1),
                    length(data_MF_FDq1),length(data_TCR_FDq1),length(data_XF_FDq1),
                    length(data_TSUR_FDq1),length(data_LL_FDq1),length(data_TFR_FDq1),
                    length(data_PF_FDq1))

data_TSCR_FDq1_padded <- c(data_TSCR_FDq1, rep(NA, max_length_FDq1 - length(data_TSCR_FDq1)))
data_TSF_FDq1_padded <- c(data_TSF_FDq1, rep(NA, max_length_FDq1 - length(data_TSF_FDq1)))
data_TUR_FDq1_padded <- c(data_TUR_FDq1, rep(NA, max_length_FDq1 - length(data_TUR_FDq1)))
data_MF_FDq1_padded <- c(data_MF_FDq1, rep(NA, max_length_FDq1 - length(data_MF_FDq1)))
data_TCR_FDq1_padded <- c(data_TCR_FDq1, rep(NA, max_length_FDq1 - length(data_TCR_FDq1)))
data_XF_FDq1_padded <- c(data_XF_FDq1, rep(NA, max_length_FDq1 - length(data_XF_FDq1)))
data_TSUR_FDq1_padded <- c(data_TSUR_FDq1, rep(NA, max_length_FDq1 - length(data_TSUR_FDq1)))
data_LL_FDq1_padded <- c(data_LL_FDq1, rep(NA, max_length_FDq1 - length(data_LL_FDq1)))
data_TFR_FDq1_padded <- c(data_TFR_FDq1, rep(NA, max_length_FDq1 - length(data_TFR_FDq1)))
data_PF_FDq1_padded <- c(data_PF_FDq1, rep(NA, max_length_FDq1 - length(data_PF_FDq1)))


FDq1_DATA <- data.frame(TSCR=data_TSCR_FDq1_padded,
                        TSF=data_TSF_FDq1_padded,
                        TUR=data_TUR_FDq1_padded,
                        MF=data_MF_FDq1_padded,
                        TCR=data_TCR_FDq1_padded,
                        XF=data_XF_FDq1_padded,
                        TSUR=data_TSUR_FDq1_padded,
                        LL=data_LL_FDq1_padded,
                        TFR=data_TFR_FDq1_padded,
                        PF=data_PF_FDq1_padded)

Box_FDq1 <-Box_data[,c(2,6)] 
Box_FDq1$MHT_TXT <- factor(Box_FDq1$MHT_TXT )

stat.test <- Box_FDq1 %>%
  mutate(FDq1 = as.numeric(as.character(FDq1))) %>%
  wilcox_test(
    FDq1 ~ MHT_TXT,
    p.adjust.method = "bonferroni"
  )

colors <- c("#982b2b", "#88c4e8", "#7E4D99","#1a9781", "pink", "#CC99BE","#0074b3","#f47720","#bdc3d2", "#db6968")


p<- ggplot(Box_FDq1)+
  # 箱线图：
  geom_boxplot(aes(MHT_TXT, FDq1, color= MHT_TXT))+
  
  # 颜色模式：
  scale_color_manual(values = colors)+
  xlab("")+
  # 主题：
  theme_classic()+
  labs(title = "FDq1")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, vjust = 1.5,face = "bold",size = 16),

        axis.text.y = element_text(size = 12, face = "bold"),
        
        axis.text.x = element_text(angle = 45, vjust = 1,hjust = 1, face = "bold",
                                   color = colors))
p
x_value <- rep(1:9, 9:1)

FDq1_DATA_no_na <- replace(FDq1_DATA, is.na(FDq1_DATA), -Inf)

y_value <- rep(apply(FDq1_DATA_no_na, 2, max)[1:9], 9:1) + 1

y_value <- y_value + c(0.3*1:9, 0.3*1:8, 0.3*1:7, 0.3*1:6,0.3*1:5, 0.3*1:4, 0.3*1:1, 0.3*1:2, 0.3)

color_value <- c(colors[2:10], colors[3:10], colors[4:10], colors[5:10], colors[6:10],colors[7:10],colors[8:10], colors[9:10],colors[10])

for (i in 1:nrow(stat.test)) {
  if (stat.test$p.adj.signif[i] != "ns") {
    y_tmp <- y_value[i]
    p <- p+annotate(geom = "text",
                    label = stat.test$p.adj.signif[i],
                    x = x_value[i],
                    y = y_tmp,
                    color = color_value[i])
  }
}

p
ggsave("FDq1.pdf", height = 6, width = 7)
```
